[[plugins]]
repo = 'Shougo/ddt.vim'
depends = 'denops.vim'
hooks_file = '$BASE_DIR/ddt.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddt-ui-terminal'
group = 'ddt'

[[plugins]]
repo = 'Shougo/ddt-ui-shell'
group = 'ddt'
