[[plugins]]
repo = 'Shougo/ddx.vim'
hooks_file = '$BASE_DIR/ddx.vim'

[[plugins]]
repo = 'Shougo/ddx-commands.vim'
depends = 'ddx.vim'
on_cmd = 'Ddx'

[[plugins]]
repo = 'Shougo/ddx-ui-hex'
group = 'ddx'
hooks_file = '$BASE_DIR/ddx-ui-hex.vim'

[[plugins]]
repo = 'Shougo/ddx-analyzer-zip'
group = 'ddx'
