[[plugins]]
repo = 'mattn/vim-notification'
hook_source = '''
vim9script
	echo 'hello ' .. 'shougo' .. ', how are you?'
'''

[[plugins]]
repo = 'mattn/vim-treesitter'
build = 'cd server && go build'
#on_event = ['BufRead', 'CursorHold']
